// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOngGiCChnIeTObbb3aKY-qLUVYNgZ7Dw',
    appId: '1:922550106651:web:2935cf540f96c35552d6be',
    messagingSenderId: '922550106651',
    projectId: 'ei-next-078-2026',
    authDomain: 'ei-next-078-2026.firebaseapp.com',
    storageBucket: 'ei-next-078-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1aVeAyWKxomz1fFthiD3xNV6yNsmT3ik',
    appId: '1:922550106651:android:53c63e14bad97a0952d6be',
    messagingSenderId: '922550106651',
    projectId: 'ei-next-078-2026',
    storageBucket: 'ei-next-078-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQK3aTZhvS5sL1Qf5GZ9MMgSj8tvQ9gT0',
    appId: '1:922550106651:ios:8b847d9ba8bd5ae952d6be',
    messagingSenderId: '922550106651',
    projectId: 'ei-next-078-2026',
    storageBucket: 'ei-next-078-2026.firebasestorage.app',
    iosBundleId: 'com.example.next',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQK3aTZhvS5sL1Qf5GZ9MMgSj8tvQ9gT0',
    appId: '1:922550106651:ios:8b847d9ba8bd5ae952d6be',
    messagingSenderId: '922550106651',
    projectId: 'ei-next-078-2026',
    storageBucket: 'ei-next-078-2026.firebasestorage.app',
    iosBundleId: 'com.example.next',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOngGiCChnIeTObbb3aKY-qLUVYNgZ7Dw',
    appId: '1:922550106651:web:d06b361c735a8dc052d6be',
    messagingSenderId: '922550106651',
    projectId: 'ei-next-078-2026',
    authDomain: 'ei-next-078-2026.firebaseapp.com',
    storageBucket: 'ei-next-078-2026.firebasestorage.app',
  );
}
